### PR TITLE
[SAC-197] Fix error when temporary views are created

### PR DESCRIPTION
**Pull request by Bongani**
## What changes were proposed in this pull request?

When creating a temporary view, an exception would be thrown. This is because temporary items can not be obtained from the spark external catalogue. Thus, temporary must be ignored. In the code, it now only tracks PersistedViews; ignoring TemporaryViews and GlobalTemporaryViews. 

## How was this patch tested?

Integration test

Manual testing as done below:

` val df = spark.read.format("csv").option("header", "true").load("employee5.csv")
df.createOrReplaceTempView("tempView")
spark.sql("Select * from tempView").write.mode("overwrite").saveAsTable("employee")
`
Which produced the following lineage:
Screenshot from 2019-03-23 23-01-32

### CODE REVIEW

**Comment by Bongani** [comment]
Hi @dongjoon-hyun & @HeartSaVioR, could you please review my pull request when you have a moment?

Thanks in advance.

**Comment by HeartSaVioR** [comment]
@Bongani 

I'm not sure we are getting exception from that query: the new test fails if I pull this PR and revert the change on SparkExecutionPlanProcessor, but the reason of failure actually represents it just works.

```
- CREATE TEMPORARY VIEW FROM TABLE, SAVE TEMP VIEW TO TABLE *** FAILED *** (28 milliseconds)
  ListBuffer(AtlasEntity{AtlasStruct{typeName='spark_process', attributes=[outputs:[AtlasEntity{AtlasStruct{typeName='spark_table', attributes=[owner:jlim, ownerType:USER, tableType:VIEW, sd:AtlasEntity{AtlasStruct{typeName='spark_storagedesc', attributes=[serde:org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, qualifiedName:local-1553489032717.default.destination_55827.storageFormat, compressed:false, inputFormat:org.apache.hadoop.mapred.SequenceFileInputFormat, outputFormat:org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat, properties:{serialization.format=1}]}guid='-474210633197', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, partitionColumnNames:[], unsupportedFeatures:[], createTime:1553489034000, qualifiedName:local-1553489032717.default.destination_55827, name:destination_55827, db:AtlasEntity{AtlasStruct{typeName='spark_db', attributes=[owner:jlim, ownerType:USER, qualifiedName:local-1553489032717.default, clusterName:primary, name:default, description:Default Hive database, locationUri:AtlasEntity{AtlasStruct{typeName='fs_path', attributes=[path:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, qualifiedName:file:/Users/jlim/WorkArea/ScalaProjects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, name:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717]}guid='-474210633196', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, properties:{}]}guid='-474210633195', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, properties:{transient_lastDdlTime=1553489034, view.query.out.col.0=name, view.query.out.numCols=1, view.default.database=default}]}guid='-474210633199', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}], executionTime:1602079, remoteUser:jlim, executionId:2, qualifiedName:local-1553489032717, inputs:[], name:com.hortonworks.spark.atlas.sql.CreateViewHarvesterSuite local-1553489032717, currUser:jlim, details:== Parsed Logical Plan ==
  CreateViewCommand `destination_55827`, false, true, LocalTempView
     +- Project [name#3068]
        +- SubqueryAlias `default`.`source_73537`
           +- HiveTableRelation `default`.`source_73537`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [name#3068]

  == Analyzed Logical Plan ==
  CreateViewCommand `destination_55827`, false, true, LocalTempView
     +- Project [name#3068]
        +- SubqueryAlias `default`.`source_73537`
           +- HiveTableRelation `default`.`source_73537`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [name#3068]

  == Optimized Logical Plan ==
  CreateViewCommand `destination_55827`, false, true, LocalTempView
     +- Project [name#3068]
        +- SubqueryAlias `default`.`source_73537`
           +- HiveTableRelation `default`.`source_73537`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [name#3068]

  == Physical Plan ==
  Execute CreateViewCommand
     +- CreateViewCommand `destination_55827`, false, true, LocalTempView
           +- Project [name#3068]
              +- SubqueryAlias `default`.`source_73537`
                 +- HiveTableRelation `default`.`source_73537`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [name#3068], sparkPlanDescription:Execute CreateViewCommand
     +- CreateViewCommand `destination_55827`, false, true, LocalTempView
           +- Project [name#3068]
              +- SubqueryAlias `default`.`source_73537`
                 +- HiveTableRelation `default`.`source_73537`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [name#3068]
  ]}guid='-474210633200', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, AtlasEntity{AtlasStruct{typeName='spark_table', attributes=[owner:jlim, ownerType:USER, tableType:VIEW, sd:AtlasEntity{AtlasStruct{typeName='spark_storagedesc', attributes=[serde:org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, qualifiedName:local-1553489032717.default.destination_55827.storageFormat, compressed:false, inputFormat:org.apache.hadoop.mapred.SequenceFileInputFormat, outputFormat:org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat, properties:{serialization.format=1}]}guid='-474210633197', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, partitionColumnNames:[], unsupportedFeatures:[], createTime:1553489034000, qualifiedName:local-1553489032717.default.destination_55827, name:destination_55827, db:AtlasEntity{AtlasStruct{typeName='spark_db', attributes=[owner:jlim, ownerType:USER, qualifiedName:local-1553489032717.default, clusterName:primary, name:default, description:Default Hive database, locationUri:AtlasEntity{AtlasStruct{typeName='fs_path', attributes=[path:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, qualifiedName:file:/Users/jlim/WorkArea/ScalaProjects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, name:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717]}guid='-474210633196', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, properties:{}]}guid='-474210633195', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, properties:{transient_lastDdlTime=1553489034, view.query.out.col.0=name, view.query.out.numCols=1, view.default.database=default}]}guid='-474210633199', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, AtlasEntity{AtlasStruct{typeName='spark_db', attributes=[owner:jlim, ownerType:USER, qualifiedName:local-1553489032717.default, clusterName:primary, name:default, description:Default Hive database, locationUri:AtlasEntity{AtlasStruct{typeName='fs_path', attributes=[path:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, qualifiedName:file:/Users/jlim/WorkArea/ScalaProjects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, name:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717]}guid='-474210633196', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, properties:{}]}guid='-474210633195', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, AtlasEntity{AtlasStruct{typeName='fs_path', attributes=[path:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, qualifiedName:file:/Users/jlim/WorkArea/ScalaProjects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717, name:/users/jlim/workarea/scalaprojects/spark-atlas-connector/spark-atlas-connector/target/tmp/sac-warehouse-4731137945549121717]}guid='-474210633196', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}, AtlasEntity{AtlasStruct{typeName='spark_storagedesc', attributes=[serde:org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, qualifiedName:local-1553489032717.default.destination_55827.storageFormat, compressed:false, inputFormat:org.apache.hadoop.mapred.SequenceFileInputFormat, outputFormat:org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat, properties:{serialization.format=1}]}guid='-474210633197', homeId='null', isProxy='false', status=null, createdBy='null', updatedBy='null', createTime=null, updateTime=null, version=0, relationshipAttributes=[], classifications=[], meanings=[]}) was not empty (CreateViewHarvesterSuite.scala:124)
```

**Comment by Bongani** [comment]
@HeartSaVioR 

Thanks for pointing that out. I picked up the test passed because I was using the same view name created by a previous unit test. I've corrected that by adding the  a new variable `destinationView3`, I'm not sure if this is okay or would you care for e to rename `destinationView` with the _before_ test annotation.

**Comment by HeartSaVioR** [comment]
@Bongani 
Never mind, your change looks good and I can see the test failing with matched reason of your observation when I revert the change. Thanks for the quick fix!

**Comment by HeartSaVioR** [comment]
Thanks @Bongani for the great efforts! I merged into master.

**Comment by Bongani** [comment]
Thanks for the merge @HeartSaVioR

**Pull request merged**
