### PR TITLE
[SAC-187][SQL] Harvest Kafka entities as input entities whenever possible in batch execution

### LINKED ISSUE #187: Harvest Kafka entities as input entities whenever possible in batch execution

### PR DESCRIPTION
**Pull request by HeartSaVioR**
## What changes were proposed in this pull request?

This patch proposes harvesting Kafka entities for both input and output in batch query. To reduce the redundant code fix, I had to refactor some code, as well as fix minor bug encountered while refactoring.

Unfortunately batch query in Kafka data source leverages Data Source v1 (even in Spark 2.4) which has to apply custom patch to retrieve parameters. 

Same issue already happened for Spark 2.3 (see below commit) and we added custom patch for Spark 2.3. The needed custom patch is fortunately same between Spark 2.3 and Spark 2.4.

https://github.com/hortonworks-spark/spark-atlas-connector/commit/aadb3c98bfd013e9bcbcdd29f65e5ed6845802ef

## How was this patch tested?

* New UT is added for batch query. 
* Existing UT for streaming query is modified as well.
* Manually tested against Spark 2.4 (custom patch applied) & Atlas 1.1

> Query case 1

```
val topicsToRead1 = Seq("s5_topic_1_3264278492_sac_187_v2_spark_2_4_b", "s5_topic_2_3264278492_sac_187_v2_spark_2_4_b")
val topicsToRead2 = Seq("s5_topic_3_3264278492_sac_187_v2_spark_2_4_b", "s5_topic_4_3264278492_sac_187_v2_spark_2_4_b")

val customClusterName = "custom_cluster"

val df = spark.read.format("kafka")
  .option("kafka.bootstrap.servers","localhost:9027")
  .option("subscribe", topicsToRead1.mkString(","))
  .option("kafka.atlas.cluster.name", customClusterName)
  .option("startingOffsets", "earliest")
  .load()

val assignForDf2 = """{"s5_topic_3_3264278492_sac_187_v2_spark_2_4_b": [0, 1], "s5_topic_4_3264278492_sac_187_v2_spark_2_4_b": [0, 1]}"""

val df2 = spark.read.format("kafka")
  .option("kafka.bootstrap.servers", "localhost:9027")
  .option("assign", assignForDf2)
  .option("startingOffsets", "earliest")
  .option("kafka.atlas.cluster.name", customClusterName)
  .load()

df.union(df2).write.mode("append").saveAsTable("s5_spark_t1_155623032_sac_187_v2_spark_2_4_b")
```

screen shot 2019-01-11 at 12 59 51 pm
screen shot 2019-01-11 at 1 00 10 pm
screen shot 2019-01-11 at 1 00 17 pm
screen shot 2019-01-11 at 1 00 23 pm

> Query case 2

```
val topicsToRead1 = Seq("s5_topic_a_3264278492_sac_187_v2_spark_2_4_b", "s5_topic_b_3264278492_sac_187_v2_spark_2_4_b")
val topicsToRead2 = Seq("s5_topic_c_3264278492_sac_187_v2_spark_2_4_b", "s5_topic_d_3264278492_sac_187_v2_spark_2_4_b")
val topicToWrite = "s5_topic_e_3264278492_sac_187_v2_spark_2_4_b"

val customClusterName = "custom_cluster"

val df = spark.read.format("kafka")
  .option("kafka.bootstrap.servers", "localhost:9027")
  .option("subscribe", topicsToRead1.mkString(","))
  .option("startingOffsets", "earliest")
  .option("kafka.atlas.cluster.name", customClusterName)
  .load()

val assignForDf2 = """{"s5_topic_c_3264278492_sac_187_v2_spark_2_4_b": [0, 1], "s5_topic_d_3264278492_sac_187_v2_spark_2_4_b": [0, 1]}"""

val df2 = spark.read.format("kafka")
  .option("kafka.bootstrap.servers", "localhost:9027")
  .option("assign", assignForDf2)
  .option("startingOffsets", "earliest")
  .option("kafka.atlas.cluster.name", customClusterName)
  .load()

df.union(df2).write
  .format("kafka")
  .option("kafka.bootstrap.servers", "localhost:9027")
  .option("topic", topicToWrite)
  .option("kafka.atlas.cluster.name", customClusterName)
  .save()

```

screen shot 2019-01-11 at 1 05 49 pm
screen shot 2019-01-11 at 1 05 57 pm
screen shot 2019-01-11 at 1 06 03 pm
screen shot 2019-01-11 at 1 06 09 pm

Please note the cluster name in Kafka entity: custom Atlas cluster name is applied.

This closes #187

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
There's some merge conflict so just created another PR for atlas-1.1 branch: #191

**Comment by HeartSaVioR** [comment]
I'll add another batch UT - `Kafka to Kafka via df.save()` soon so that `SaveIntoDataSourceHarvester` is also covered as well. The change will be also applied to #191.

**Comment by HeartSaVioR** [comment]
Let me add WIP again... I realized we can't discover any Kafka topics in executed plan from some kinds of batch queries.

```
val df = spark.read.format("kafka")
      .option("kafka.bootstrap.servers", kafkaTestUtils.brokerAddress)
      .option("subscribe", topicsToRead.mkString(","))
      .option("startingOffsets", "earliest")
      .load()

    val customClusterName = "customCluster"
    df.union(df).write
      .format("kafka")
      .option("kafka.bootstrap.servers", kafkaTestUtils.brokerAddress)
      .option("topic", topicToWrite)
      .option("kafka." + AtlasClientConf.CLUSTER_NAME.key, customClusterName)
      .save()
```

Here's the executed plan of above query:

```
Execute SaveIntoDataSourceCommand
   +- SaveIntoDataSourceCommand org.apache.spark.sql.kafka010.KafkaSourceProvider@49482761, Map(topic -> sparkwrite, kafka.atlas.cluster.name -> customCluster, kafka.bootstrap.servers -> 127.0.0.1:52329), ErrorIfExists
         +- Union
            :- Relation[key#0,value#1,topic#2,partition#3,offset#4L,timestamp#5,timestampType#6] KafkaRelation(strategy=Subscribe[sparkread1, sparkread2, sparkread3], start=EarliestOffsetRangeLimit, end=LatestOffsetRangeLimit)
            +- Relation[key#0,value#1,topic#2,partition#3,offset#4L,timestamp#5,timestampType#6] KafkaRelation(strategy=Subscribe[sparkread1, sparkread2, sparkread3], start=EarliestOffsetRangeLimit, end=LatestOffsetRangeLimit)
```

`KafkaRelation` looks like the only thing to safely get it across various kinds of batch query, but two things are changed then:

* It requires another kind of custom patch in Spark side to modify KafkaRelation to convert constructor parameters `ConsumerStrategy`, and `specifiedKafkaParams` to fields in KafkaRelation
* We can't get actual list of topics when topic pattern is provided, whereas current new UT properly extracts actual topics.

Personally, having clear limitation sounds better than showing behavior some queries works and some queries don't. And then we need to only rely on `KafkaRelation`. Some of part in #188 would help changing the PR.

**Comment by HeartSaVioR** [comment]
I've updated the patch, as well as updated description via new manual tests.

**Comment by dongjoon-hyun** [comment]
Thank you, @HeartSaVioR . I know that the test is a big headache now.

**Comment by HeartSaVioR** [comment]
CI build is green and manual tests are done. Merging.

**Comment by HeartSaVioR** [comment]
@dongjoon-hyun Thanks for reviewing!

Regarding tests, actually I'm in favor of adding acceptance tests, adding known cases as many as possible in `SparkExecutionPlanProcessorForBatchQuerySuite` and `SparkExecutionPlanProcessorForStreamingQuerySuite`.

I wish to add various of queries with matrix of input / outputs to not fear of regression, but SAC links SHC/SWC via reflection, as well as we require custom patch for spark-sql-kafka, unfortunately this is going to be hard one to achieve.

**Comment by dongjoon-hyun** [comment]
Yep. It's not possible in Apache domains.

**Pull request merged**
